- name: Install and Configure Apache Web Server
  hosts: webservers
  become: yes

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache2 web server
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a simple HTML file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Restart Apache2 service
      service:
        name: apache2
        state: restarted