name: TSSAD

on:
  push:
    branches:
      - Staging
  pull_request:
    branches:
      - Prod
  workflow_dispatch:

jobs:
  terraform-security-scan:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Run TFLint
        run: |
          curl -sL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
          tflint

  terraform-deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    needs: terraform-security-scan
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout terraform
        uses: actions/checkout@v3
        with:
          ref: Staging

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID=ASIAXHSQPKZ7UYWMDBFH
          export AWS_SECRET_ACCESS_KEY=4jI6/I1PYISCEvBcVNPl0kg2U5Oumtw3e2c5VgOY
          export AWS_REGION=us-east-1

      - name: Debug - List files
        run: ls -R

      - name: Terraform Init
        run: terraform -chdir=./modules/network init

      - name: Terraform Plan
        run: terraform -chdir=./modules/network plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=./modules/network apply -auto-approve tfplan
